services:
  - type: web
    name: websocket-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 server_render.py
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000

