services:
  - type: web
    name: esp32-test-q46k
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn render_server:app --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 120
    healthCheckPath: /

